services:
  - type: web
    name: lacc-faculdade-serra-dourada
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
    plan: free

